name: Link Check
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  lychee:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
       - name: Install lychee
         run: |
           # Install lychee using Homebrew (macOS)
           brew install lychee

       - name: Link Checker
         run: |
           lychee --no-progress --max-concurrency 8 --verbose --exclude-mail .